### ISSUE TITLE
Add support for 'serialize' jquery method

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#104]
http://api.jquery.com/serialize/

Currently, when applying the 'serialize' method over the form that contains a masked input, results in retrieving the masked data instead of the original one, which breaks server-side validation in my case. The 'autounmask' parameter has no effect.

**Comment by RobinHerbots** [comment]
That is because, the autounmask works a bit differently depending the
browser.

In FF it should work as expected. Because this browsers support to redefine
build in properties like value.  In the others it works when you or other
plugins retrieve the value by the jquery.val function.
It is implemented with some kind of fallback functionality.  When
redefinition of properties isn't supported then I patch the jquery.val
function to handle the autounmask.

Anyway, maybe I can write a little hack which adapts the serialize function
so it gets its value via jquery.val.

best regards,

Robin

2012/8/6 chetzof <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
Can you try by including the following code after jquery

jQuery.param = function( a, traditional ) {
    var prefix,
        s = [],
        add = function( key, value ) {
            // If value is a function, invoke it and return its value
            value = jQuery.isFunction( value ) ? value() : ( value == null ? "" : value );
            s[ s.length ] = encodeURIComponent( key ) + "=" + encodeURIComponent( value );
        };

```
// Set traditional to true for jQuery <= 1.3.2 behavior.
if ( traditional === undefined ) {
    traditional = jQuery.ajaxSettings && jQuery.ajaxSettings.traditional;
}

// If an array was passed in, assume that it is an array of form elements.
if ( jQuery.isArray( a ) || ( a.jquery && !jQuery.isPlainObject( a ) ) ) {
    // Serialize the form elements
    jQuery.each( a, function() {
        add( this.name, $(this).val() );
    });

} else {
    // If traditional, encode the "old" way (the way 1.3.2 or older
    // did it), otherwise encode params recursively.
    for ( prefix in a ) {
        buildParams( prefix, a[ prefix ], traditional, add );
    }
}

// Return the resulting serialization
return s.join( "&" ).replace( r20, "+" );
```

};
