### ISSUE TITLE
IsValid on Optional Mask returning false

### ISSUE THREAD

**Issue by pricejt** [RobinHerbots/Inputmask#1055]
Why would this return false
var isValid =Inputmask.isValid(maskedString, { alias: "99-99 [99/99]"});

If my input was 03-11

I also tried with including the space var isValid =Inputmask.isValid(maskedString, { alias: "99-99[ 99/99]"});

still returns false.

**Comment by RobinHerbots** [comment]
@pricejt , 

I will verify & fix the issue, but I'm very busy on the dependencyLib.  So some patience.

The vanilla dependency is finished but all unittest need to be updated and that are a lot of tests. ;-/

**Comment by RobinHerbots** [comment]
@pricejt , 

Works in the latest version. (space needs to be included as optional)

http://jsfiddle.net/7vkpwzwm/1/

**Comment by pricejt** [comment]
@RobinHerbots ,

How do i pull only the part of the mask that is filled in? 
For example my mask is 99-99[ 99/99]
If the user only enters 03-11
If i pull the value from the text box the user is entering in the value will equal 
03-11 **/**
which is valid returns false 
    var isValid =Inputmask.isValid(maskedString, { alias: "99-99[ 99/99]"});
https://jsfiddle.net/za3omccc/

**Comment by RobinHerbots** [comment]
@pricejt , 

Hmm, ... have a look at https://jsfiddle.net/za3omccc/1/, but that is not exactly what you want.

Normally you should not check wheter the value is valid in the onComplete as that function already implies that it is valid.  The isValid function is very strict in validation.  

Getting the unmaskedvalue is also not an option because then you will get 0311 instead of 03-11.

I will make the return value the same as you see on the screen.  When the clearMaskOnLostFocus, the trailing tail will be cleared in the value when it is optional.  (as you see in the UI side)

**Comment by pricejt** [comment]
@RobinHerbots ,

Alright i don't know why i had the check for is valid that might of been so old code. I will just remove it. Sorry about that.
