### ISSUE TITLE
mask is getting lost after setting value of input field twice, without click into inputfield in between

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#110]
Hello,

i created a jsfiddle for that:
http://jsfiddle.net/CXAZx/
1. if i set the input-value once and click into the input, the the mask is still there
2. if i set the input-value once, click into the input, then set the value again, the the mask is still there
3. issue: if i set the input-value once, then immediatley set another value afterwards, the the mask is LOST.

**Comment by RobinHerbots** [comment]
Hi wuSam,

I will have a look at it this evening.

best regards, 

Robin

**Comment by ghost** [comment]
maybe this helps: if i set "greedy:true", then it works.
i'm not sure if my usage of "greedy:false" is evil or if something else is wrong.
looking forward for your answer or patch :-)

Sam

**Comment by RobinHerbots** [comment]
Checkout the latest version ;-)

**Comment by RobinHerbots** [comment]
It has todo with the greedy: false option; the mask is active but visible
when performing  $('#txtECode').val('01');

$('#txtECode').inputmask({mask:'99 999 999 999 9999', greedy:false,
autoUnmask:true});
$('#txtECode').val('01');

already introduces the behavior.

Fixed in the latest version.

2012/9/10 wuSam notifications@github.com

**Comment by ghost** [comment]
thanks!! great plugin, great reactiontime
