### ISSUE TITLE
Optional mask 9[99999] not respect maxlength attribute in Moto G 3 and Quantum Go

### ISSUE THREAD

**Issue by mbraz** [RobinHerbots/Inputmask#1430]
Hi Guys!

The mask above not run correcting in: 

Moto G 3
Navegador Chrome ( versão53.0.2785.124)
Android 6.0

Quantum Go
Navegador Chrome (versão 54.0.2840.68)
Android 5.1.0

I'm using the maxlength=6, but the mask permit only 2 positions!

<input type="text" class="form-control" id="{$id}" name="{$id}" value="{$value}" maxlength="6"
	autocomplete="on" 
	data-inputmask-mask="9[99999]"
	data-inputmask-clearmaskonlostfocus="true"
	data-inputmask-showmaskonfocus="false"
	data-inputmask-showmaskonhover="false" 
	data-inputmask-greedy="false" 
..
../>

Thanks

**Comment by RobinHerbots** [comment]
@mbraz , 

On android the key-events aren't always triggered and thus we use the input-event as fallback.  The way is work is like allow whatever entered and fix it asap.  But this means, .... when you type 12  you get 12____ due to your mask used, which already takes 6 chars.  Entering 3 is not allowed due to the maxlength of 6.

When you remove the maxlength it will work or try 9{1,6} as mask
