### ISSUE TITLE
Something stopped working in 3.3.4

### ISSUE THREAD

**Issue by oledid** [RobinHerbots/Inputmask#1496]
ES6 JSPM setup:

```js
import $ from "jquery";
import "jquery.inputmask";
import "jquery.inputmask/dist/inputmask/inputmask.date.extensions";

// [...]

$("input").inputmask("h:s", {
    "placeholder": "XX/XX",
    "insertMode": false,
    "clearIncomplete": true
});
```

JSPM override:
```js
"npm:jquery.inputmask@3.3.3": { // the version was correct when I used 3.3.4
  "shim": {
    "jquery.inputmask": [
      "jquery"
    ]
  },
  "dependencies": {
    "jquery": "*"
  }
}
```

Does nothing in 3.3.4. I get no errors. Works fine in 3.3.3. I rolled back.

**Comment by RobinHerbots** [comment]
@oledid ,
See the changelog. Those definitions are removed.  Put them back in your code and it will work. The datetime alias will allow  to pass a formatting in the future

**Comment by oledid** [comment]
Ok, thanks.

A bit of constructive feedback:
I would not recommend putting breaking changes inside a patch.

Read about semver [here](https://docs.npmjs.com/misc/semver) or [here](http://semver.org/).

**Comment by RobinHerbots** [comment]
Yes  I know

Op do 19 jan. 2017 19:36 schreef Ole Morten Didriksen <
notifications@github.com>:

Ok, thanks.

A bit of constructive feedback:
I would not recommend putting breaking changes inside a patch.

Read about semver here <https://docs.npmjs.com/misc/semver> or here
<http://semver.org/>.

—
You are receiving this because you modified the open/close state.


Reply to this email directly, view it on GitHub
<https://github.com/RobinHerbots/Inputmask/issues/1496#issuecomment-273859570>,
or mute the thread
