### ISSUE TITLE
Change event doesn't fire after change

### ISSUE THREAD

**Issue by newmangreen** [RobinHerbots/Inputmask#1561]
Input's change event is not fired after change. Event listener is registered with standard addEventListener function. Tested it in IE 11 and Chrome.

[https://jsfiddle.net/newmangreen/63ggzj5L/](https://jsfiddle.net/newmangreen/63ggzj5L/)

**Comment by RobinHerbots** [comment]
@newmangreen , 

This is a jquery thing not an issue of the inputmask.  You have 2 options.
Option 1:
When using jquery use the events from jquery and not events bound with addEventListener.  The inputmask triggers the jquery change event when using jquery as dependencylib.

Option2:
Use the vanilla dependencylib instead of jquery.  This will trigger the "native" change event.

**Comment by newmangreen** [comment]
Our case is option2. I added "dependencyLibs/inputmask.dependencyLib.js" above "jquery.inputmask.bundle.js" and it worked now. 
Thank you. (I saw it in issues but didn't add above bundle.js and it didn't work, I think this needs to be included in documentation)

**Comment by RobinHerbots** [comment]
@newmangreen , 

Feel free to submit a PR with an updated readme
