### ISSUE TITLE
Mobile Problem

### ISSUE THREAD

**Issue by rchapon** [RobinHerbots/Inputmask#1585]
Hello Robin, Firstly I want to thank You for a great plugin.

My issue is with browser mobile, I implement the plugin in my webside, and when I focus de input mail, and phone, the mask and the characters no have color, on desktop work fine, but mobile isn't work.

please visit webside on brower mobile. This is it www.dewym.com.ve

Thank You.

**Comment by rchapon** [comment]
Hello Robin, a few days I wrote you about a problem, if you can answer the question I will be glad

**Comment by rchapon** [comment]
Hello Robin, I put color to input with focuin, but now it show mask like password type. It show ***********

**Comment by RobinHerbots** [comment]
@rchapon , 

I had a quick look at your site and you applied the android hack.  So you see the password type due to the hack applied, but it seems that the positioning of the mimicking div is wrong.  You can read about it in the android readme.

Try to set the colorMask: true option so you can more easily debug on a desktop browser.  As the last element of the body you will find the created div.  Find out why it is positioned badly.

**Comment by RobinHerbots** [comment]
@rchapon , 

I updated the colorMask option in the 4.x branch, it should better handle the positioning and can easily tweaked by the inputmask.css.  Have a try.
