### ISSUE TITLE
How create mask like hhh:mm ?

### ISSUE THREAD

**Issue by SkyTaurus** [RobinHerbots/Inputmask#1662]
I need to take into account the hours and minutes, the clock can be more than 100. The mask hh:mm does not suit me.

**Comment by thanhhau89** [comment]
I have problem same

**Comment by RobinHerbots** [comment]
@SkyTaurus ,  @thanhhau89 , 

So the hours are unlimited and the minutes from 0-59  ?  I will add something like that into the datetime alias but maybe something like this?

```
 Inputmask({
            regex: "\\d+:[0-5][0-9]"
        }).mask("test5");
```

**Comment by thanhhau89** [comment]
hi @RobinHerbots ,

thank you for reply.

I try using 
$("#inputID").inputmask("datetime", { inputFormat: "HH:MM", "clearIncomplete": true });

It's OK.

But I see a problem in config **HH: "[01][0-9]|2[0-4]",**, I think **HH: "[01][0-9]|2[0-3]",**.
Example : 24 : 59 => 00 : 59

**Comment by RobinHerbots** [comment]
@thanhhau89 , 

Yes, you are right.  I will adjust the definition.

**Comment by natts1** [comment]
Hi @RobinHerbots, thanks for all your work on Inputmask. I'm having a problem with trying to implement HHH:MM as an inputformat, with v4. This is what I have:
```javascript
$('input#time').inputmask('999:99', {
  alias: 'datetime',
  inputFormat: 'HHH:MM',
  clearIncomplete: false,
  numericInput: true,
  placeholder: '00:00',
});
```
The requirement is that typing the characters `15789`, for instance, would be adjusted from `157:89` to `157:59`, because the minutes would be validated and corrected. Or, simply typing `67` changes what's in the input box from `000:67` to `000:59`, or even converting it to `001:07`.

Is this what ought to be possible, and if so, have I made a mistake in my implementation of the datetime extension, or is there a bug in the extension/inputmask itself? Possibly it's because I'm using numericInput, or not using clearIncomplete? I also had to set the placeholder to `00:00` instead of `000:00`, as the latter breaks the formatting (double colon in the centre).

**Comment by RobinHerbots** [comment]
@natts1 , 

This is not possible with the datetime alias.  But you can use something like the below
```
$('input#time').inputmask('999:99', {
  numericInput: true,
  placeholder: '0',
    postValidation: function (buffer, pos, currentResult, opts) {
                //check buffer value
               // var correctedBuffer = correct the buffer acording the required logic

               //     if (buffer needs to be corrected) {
               //         return {
               //             buffer: correctedBuffer,
               //             refreshFromBuffer: true
               //         };
               //     }

                    return true;
                }
});
 ```
