### ISSUE TITLE
date format 'mm/dd/yyyy' always yields '10' for day values between 13 and 19

### ISSUE THREAD

**Issue by oliverlangan** [RobinHerbots/Inputmask#1683]
```
$input.inputmask("mm/dd/yyyy").val('10/19/2017');
```

Currently yields "10/10/2017".

Introduced in 3.3.8, works correctly in 3.3.7.

**Comment by ignatiusabraham** [comment]
I have a similar issue in yii2 input mask. Please post your solution if you issue has been resolved thanks in advance

**Comment by RobinHerbots** [comment]
@oliverlangan ,  @ignatiusabraham ,

See https://github.com/RobinHerbots/Inputmask/projects/1

**Comment by rmulhol** [comment]
@RobinHerbots I'm interested in working on this issue. However, could you provide instructions about running the tests? When I `npm install` and then `npm run test` it fails due to errors and warnings in the eslint step. I tried running just `grunt karma`, but that shows 9 test failures. Figure I must be missing a build step (although I tried `grunt build` to no avail).

**Comment by RobinHerbots** [comment]
Hi @rmulhol , 

Don't worry about the 9 failures, those are issues yet to be resolved.
Are you interested in only solving the issue or in the new datetime project?

For the issue, you need to work on the 3.x branch, for the new datetime you use the 4.x branch.

Anyway, it would be great because I don't have much time free to spend.

**Comment by RobinHerbots** [comment]
This is fixed in the 3.x branch.  It was due to a pull request.  I reverted it. I will releasee 3.3.10 today or tomorrow.

**Comment by RobinHerbots** [comment]
@oliverlangan , 

Have a try with version 3.3.10

**Comment by oliverlangan** [comment]
@RobinHerbots, verified fixed with 3.3.10. Thanks!
