### ISSUE TITLE
Why UK phone converts to Korea phone?

### ISSUE THREAD

**Issue by dmitrimag** [RobinHerbots/Inputmask#1687]
Hi. I tried to use phone mask. But when typed +44 (UK) and got more than 16 symbols at all that phone converted into +850 (North Korea - wtf?). I think it's not good cause +1 (USA) doesnt give you opportunity to type more symbols than predefined mask want.
Also tried here - http://robinherbots.github.io/Inputmask/
Same result. Any ideas to fix it?

P.S.
Not only for UK numbers. Cant identify condition.
Version - 4.0.1-37
Tested in desktop Chrome, Firefox, IE.

**Comment by wistala** [comment]
Is there any solution about this problem. I am having same problem while typing other numbers it is converting the number to korean phone number. The problem is usually occuring if you continue to type after the phone number is completed. It is like a timer is waiting the end of the keypresses and script revealing this error.

**Comment by RobinHerbots** [comment]
Remove Phone alias #1981
