### ISSUE TITLE
How to indicate custom mask being used in tag argument?

### ISSUE THREAD

**Issue by tomaszs** [RobinHerbots/Inputmask#1711]
For basic mask i can use this notation (based on the readme):

<input data-inputmask="'mask': '99-9999999'" />

There is also an extension phoneus

How should i change above notation to indicate i want to use extension mask called phoneus?

**Comment by RobinHerbots** [comment]
@tomaszs ,

use the alias option

data-inputmask-alias="phoneus"

**Comment by tomaszs** [comment]
Thank you Robin

**Comment by lvmajor** [comment]
Specifying data-inputmask-alias="phoneus" gives me a textual value of "phoneus" in the input field. 
Is there a particular file to load? I used the jquery files (jquery, jquery.inputmask.bundle.js and inputmask/phone-codes/phone.js)

**Comment by RobinHerbots** [comment]
@os1r1s110 ,

Yes, you need to include the phone-us.js

**Comment by lvmajor** [comment]
Ah I see, it is because it is missing from the files obtained through npm :)

Thanks for the info, I will download the repo manually and include it in my local node_modules folder

Ouch, I just saw the filesize.... that's impressively big (17MB)....  If I may ask a question, what is the end purpose of those files? Is it to automatically change the mask relative to the phone-code?

I'm not sure I fully understand the goal of this file and to find out if I really need it or not.

**Comment by RobinHerbots** [comment]
@os1r1s110 , 

It is included in the npm package, but you need to import it separately.

Have a look at the index.js used by npm

```
require("./dist/inputmask/inputmask.date.extensions");
require("./dist/inputmask/inputmask.extensions");
require("./dist/inputmask/inputmask.numeric.extensions");
require("./dist/inputmask/inputmask.phone.extensions");

// require("./dist/inputmask/phone-codes/phone-be");
// require("./dist/inputmask/phone-codes/phone-nl");
// require("./dist/inputmask/phone-codes/phone-ru");
// require("./dist/inputmask/phone-codes/phone-uk");
// require("./dist/inputmask/phone-codes/phone");

module.exports = require("./dist/inputmask/inputmask.js");
```
Only use the phone extension if you really need it for a purpose.  The phone-us is a contributed file.  I would more use a regional phone code or more general which can be much smaller.
The phone codes contain all possible variations.  It is up to the developer to reduce the list according the requirements.

**Comment by lvmajor** [comment]
Effectively I understand that we can trim the files according to our needs, but what does it actually do?
Does it change mask according to what we first input? How does it know which "region/city" to use?

As for the files to input, they are not found under the dist folder (the links you mentioned are there, but not for phone-us and phone-ca yet)

**Comment by RobinHerbots** [comment]
@os1r1s110 , 

Tobe honest I haven't looked at the phone-us & phone-ca files yet.  They are indeed huge!!  And about the purpose, ... the mask format stays always the same, so there is not really a need besides that you can request the metadata.  The main purpose is that the inputmask changes the mask according the differences between phone format for country or region.  Have a look at phone.js.  You can also request the metadata, which will return the metadata depending on you input.

In this case, I guess the only purpose is to be able to request the metadata.

Can my plugin handle this amount of masks?  I will have a try ;-)

**Comment by lvmajor** [comment]
Okay thanks for the clarification :)

**Comment by RobinHerbots** [comment]
#1676

**Comment by Josh68** [comment]
It appears to me that `phone-us.js` is gone and there's some misleading notes in the source that `phone-ca.js` contains both CA and US phone metadata. Like everyone else is saying, they're so huge, you'd have to have a good reason to load one, but can someone figure out what's up with `phone-us`?

**Comment by RobinHerbots** [comment]
@Josh68 , 

The phone-us is so huge that it just doesn't work.  I moved the file to the misc folder.  Eventually, when I review the phone masking, I can put it back next the others.

**Comment by Josh68** [comment]
@RobinHerbots, thanks for the info (and the excellent library). Maybe this is a feature that's too ambitious. Sounds great for particular use-cases, but not only are these files huge, I'm sure they'll also become outdated quickly (unless you have some automated way of keeping them up-to-date). I only even tried grabbing it because I wanted to see if there was a specific mask/alias that didn't use the CC. Still working with that using the basic `phone` alias and trying to extend. I was not after all the extra features that the `phone-codes` files offer.
