### ISSUE TITLE
inputmask('integer') does not works on Android, any input discarded

### ISSUE THREAD

**Issue by michelevirgilio** [RobinHerbots/Inputmask#1737]
Hi Robin,
i've an issue when i use inputmask('integer'): on desktop is fine, but testing on Android, the text input does not accepts any chars, both alpha and numerics.
Any clue?
Thanks

**Comment by RobinHerbots** [comment]
Hi @michelevirgilio , 

Which version of the inputmask are you using?

**Comment by michelevirgilio** [comment]
3.3.9
Thanks

**Comment by RobinHerbots** [comment]
For testing

https://jsfiddle.net/vvy1fdz0/

**Comment by RobinHerbots** [comment]
@michelevirgilio , 

Have a try with the jsfiddle (4.x) or try version 3.3.10

**Comment by bcardiff** [comment]
@RobinHerbots I've [tested 3.3.10](https://jsfiddle.net/bcardiff/a4wukgsd/1/) on a moto e with android 4.4.4 and chrome 62.0.3202.73 and the problem mentioned in this thread is still present when the predictive keyboard is enabled.

If [androidHack is used](https://jsfiddle.net/bcardiff/a4wukgsd/2/), I see the password field on android phones.  I try to use [colorMask + css](https://jsfiddle.net/bcardiff/a4wukgsd/3/) but the additional field is still present.

The good news is that the [4.x fiddle](https://jsfiddle.net/vvy1fdz0/) seems to be working as expected for now, but since it's not released, I would like to ask what is the status for releasing 4.x to the wild.

Thanks for this library!

**Comment by RobinHerbots** [comment]
@bcardiff , 

Have a try with https://jsfiddle.net/a4wukgsd/4/
It seems that the css in the 3.3.10 version is incomplete.

Btw you also need to include the css when using the androidhack

**Comment by RobinHerbots** [comment]
I released 3.3.11 with updated css.

4.x release will be when regex support and the datetime alias is on par with the 3.x branch

**Comment by bcardiff** [comment]
Thanks @RobinHerbots for the release.
I would like to ask two things that might lead to other new issues.

1. If the original inputs are styled, when androidHack is used, I am expected to tweak the css in this repo to mimic the original look and feel, right? If so, that should be done solely in css since I couldn't find any callback to add css classes to the additional div helper.

2. I noticed, that if many input masks are present in the same page, when the user clicks on them (without pressing any key), multiple blink cursors will end up been displayed. http://g.recordit.co/pNRUhoJrlf.gif

At the end of the day I am trying to use input mast with a bootstrap 3.3.7 site:
https://jsfiddle.net/bcardiff/a4wukgsd/5/ that's why I noticed (1). And might found some stopper issues regarding bootstraps input addons and inputmask working together.

**Comment by RobinHerbots** [comment]
@bcardiff , 

The issues you see in the layout in the bootstrap styled inputs are due to the colorMask (~ androidHack) used.  I opened a new issue to follow-up on these.  
issue 1: yes, maybe allowing to pass a ccssclass or inheriting the cssclass from the input could help
issue 2: I will fix that
Suggestions, feedback, ideas, solutions are welcome.
