### ISSUE TITLE
inputmask("phone") perfomance problem

### ISSUE THREAD

**Issue by echocompany** [RobinHerbots/Inputmask#1783]
used scripts:
<script src="dist/jquery.inputmask.bundle.js"></script>
<script src="dist/inputmask/phone-codes/phone.js"></script>
<script src="dist/inputmask/phone-codes/phone-ru.js"></script>

init:
$('.inputmask').inputmask('phone');
![2018-01-06_22-36-46](https://user-images.githubusercontent.com/14230361/34642446-f5a7897c-f334-11e7-9656-3ec7045eaa09.png)

latency ~200-300 ms

init:
$('.inputmask').inputmask('+9 (999) 999-99-99');
latency ~40 ms

Is it possible to solve this problem?

**Comment by RobinHerbots** [comment]
Can you provide some more information. Are you talking about lag on init or is this lag on input?

Which version do you use, platform, browser?

**Comment by echocompany** [comment]
Lag On init
Windows 10, Chrome 63.0.3239.84

**Comment by RobinHerbots** [comment]
@echocompany , 

This is due to the preprocessing of the many masks used for the phone & phone-ru.  Maybe I can do some kind of precompilation of the masks.  Anyway this will be low priority at the moment.  I'm currently enhancing the alternations and looking to speedup the input-response when using many masks like the phone-masks.  I'm also trying to reduce the code base.

**Comment by echocompany** [comment]
ok, we'll wait.

Thanks for your work!

**Comment by RobinHerbots** [comment]
Remove Phone alias #1981
