### ISSUE TITLE
Lost 0 on left side numeric value

### ISSUE THREAD

**Issue by fleonardelli** [RobinHerbots/Inputmask#1883]
Hi. I want to use currency format, everything is working good, but I'm loosing 0 when set the value from JS. 

Here is an example. I see someone posted the same issue years ago, but I didn't find the solution. 

https://jsfiddle.net/cecey8Ly/

**Comment by fleonardelli** [comment]
Great, It's working!!  But look at the fiddle now, setting 2000.00

**Comment by RobinHerbots** [comment]
@fleonardelli , 

Have a look at https://jsfiddle.net/cecey8Ly/3/

**Comment by fleonardelli** [comment]
Working! thanks!!

**Comment by fleonardelli** [comment]
@RobinHerbots 

Again here, is there any way to put the caret on the right ?

**Comment by awalakaushik** [comment]
@RobinHerbots I have something that is similar to this issue. Since it is open, I thought this would be the appropriate place to put the question in. If we take the example above, https://jsfiddle.net/cecey8Ly/3/ and let's say, we have ssn value which consists of 9 digits and we want to be able to mask the numbers starting with zero as valid SSN, how would we do that? 
Right now, if we add the mask alias as numeric and specify the integer digits as 9, we cannot enter SSN values without a zero because the mask removes the leading 0 from the number.
**Sample test case**
_Actual Value:_ 012345678. 
_Masked Value_: 12345678

**Comment by RobinHerbots** [comment]
https://jsfiddle.net/vb4omLga/1/
