### ISSUE TITLE
InputMask not getting fresh placeholder value

### ISSUE THREAD

**Issue by brxkensmile** [RobinHerbots/Inputmask#2111]
**Describe the bug**
If I initialized InputMask for my input and then I want to update text in placeholder, InputMask will change new placeholder to old (on click, mouseleave mb other events too).  

**Live example**
https://codepen.io/anon/pen/wboEzP

**Comment by Faizan-Shakeel** [comment]
Same problem, please share if you found any solution, thx.

**Comment by RobinHerbots** [comment]
@dogzy123 ,  @Faizan-Shakeel , 

This is because the original placeholders gets stored internally on init of the inputmask.  On focus/click/hover the placeholder is replaced by the masktemplate.  On leave/blur the original placeholder is restored.  So when you in the meanwhile change the placeholder, the inputmask isn't aware of the change and restores the first (old/original) placeholder.

- A solution could be to check if the placeholder is different from the masktemplate before restoring and updating the stored original placeholder.  
- Another solution could be to rewrite the placeholder property, so setting the property could notify the inputmask.
- or stop using the placeholder to show the masktemplate, ...

**Comment by brxkensmile** [comment]
> Same problem, please share if you found any solution, thx.

For temporary solution I've added on 'onclick', 'mouseleave' & 'onblur' events such function :
```javascript
setTimeout( e => e.target.input.placeholder = "new value", 1);
```

**Comment by Faizan-Shakeel** [comment]
I simply tried removing events altogether
input.off('mouseleave mouseout')

masking is still working as expected.
thanks.

**Comment by RobinHerbots** [comment]
@dogzy123 , @Faizan-Shakeel , 

I fixed the issue in the beta branch (5.x)

https://codepen.io/robinherbots/pen/arWOqd

**Comment by brxkensmile** [comment]
Thank you!
