### ISSUE TITLE
Paste a phone number in inputmask

### ISSUE THREAD

**Issue by avxkim** [RobinHerbots/Inputmask#2213]
- If i have a mask, like `+7 (799) 999-99-99`, then it would be `99 999 99 99` in unmasked mode, but if i paste a full number, e.g.: 77001112233 - it would cut my last two numbers `33`, is it possible to cut the first number, so on paste i would get a correct number?

- OS: Catalina 10.15.1
- Chrome 78
- Inputmask version - 4.0.1

**Comment by RobinHerbots** [comment]
@webcoderkz , 

 It is impossible to handle all cases out-of the -box because the desired behavior will vary depending the mask pattern.  In version 5 it is sufficient to add a +.  +77001112233 will mask like +7 (700) 111-22-33.  (I haven't tested in version 4.0.1)

You can manipulate the pasted value by using the onBeforeMask or onBeforePaste option (see readme).
