### ISSUE TITLE
Caret Positioning broken when input is within a shadow dom

### ISSUE THREAD

**Issue by honboubao** [RobinHerbots/Inputmask#2247]
When the text input element is part of the shadow tree of a web component, the caret always jumps to the end after any input.

This happens because the call to the caret() function doesn't actually set the caret position because of this line https://github.com/RobinHerbots/Inputmask/blob/5.0.0/lib/maskScope.js#L1956

When the focused input field is within a shadow dom, document.activeElement will be the element, for which the shadow dom was created and the input will actually be set on e.g. webComponent.shadowRoot.activeElement

**Comment by RobinHerbots** [comment]
@honboubao , 

Do you have a working example to test with?

**Comment by RobinHerbots** [comment]
This can be usefull

https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot

**Comment by honboubao** [comment]
Hi Robin!

sorry, I didn't wanna be rude and just drop this on your head without as much as a hello. I was just in a hurry but didn't want to wait to bring this to your attention.

Here is a reduced example that demonstrates the issue: https://plnkr.co/edit/iqwYXuwS3fGZO99uiXO3

**Comment by RobinHerbots** [comment]
@honboubao , 
No problem, I completely understand ;-)
Thank you for bringing this issue up.  Removing the activeelement check make it all work in the shadowdom, but I want to investigate it a bit more profound, ... maybe integrate it and add support for an inputmask htmlelement, ...

**Comment by RobinHerbots** [comment]
@honboubao , 

I added the input-mask html element.  If you want to use your own, you need to set the shadowRoot in the inputmask property on the input.
```
   class SuperDuperTextfield extends HTMLElement {
              constructor () {
                  super();
                  var shadow = this.attachShadow({ mode: "closed" });
                  var input = document.createElement("input");
                  input.type = "text";
                  shadow.appendChild(input);
                  
                  new Inputmask({ mask: "9999-999-9999" }).mask(input);
                  input.inputmask.shadowRoot = shadow;
              }
          }
          
          customElements.define("super-duper-textfield", SuperDuperTextfield);
```

**Comment by artvel** [comment]
Hi @RobinHerbots 
I'm investigating this case and I thought before I create a pull request out of nothing I inform you about my suggestion.
I decided to write here because the issue is not fixed yet. I tested your `Inputmask` inside a web-component.

First of all, I am not even sure if `input.inputmask.shadowRoot` is solving any case. But anyways, instead of differentiating between shadowRoot and document like you do in this line https://github.com/RobinHerbots/Inputmask/blob/ffeb767377b9b928ec3f9cb75af14d263a4cbbf3/lib/eventhandlers.js#L317

I would implement a method like:
```
function docGetActiveElement(){
 let el;
 let target = document;
 while(el = target.activeElement){
  if(el.shadowRoot){
     target = el.shadowRoot;
  } else {
    break;
  }
  return el;
}
```

This would solve all the cases if I am not wrong.. even the one you tried to fix with `input.inputmask.shadowRoot`.

```
if (docGetActiveElement() !== input) {
	input.focus();
}
```

What do you think @RobinHerbots ?

**Comment by RobinHerbots** [comment]
@artvel ,

I assume the issue occurs when you use the inputmask in your own web-component?
In that case the inputmask.shadowroot will always be undefined and it will not work.  Have a look at the inputmaskelement.js to see where the shadowroot gets defined.

I agree to put the (input.inputmask.shadowRoot || input.ownerDocument).activeElement in a separate funtion (module).
(use getActiveElement)

I read in https://developer.mozilla.org/en-US/docs/Web/API/Element/shadowRoot that I can check for the shadowRoot directly on the input itself. So I do not need to keep the shadowRoot myself.

About your code why do you need the while loop?

**Comment by artvel** [comment]
@RobinHerbots 

because the actual issue is recursion.
Depending on how many web-components you have and if they are nested..
activeElement returns the next web-component with shadowRoot if the input is inside a web-component and it is active.

**Comment by artvel** [comment]
@RobinHerbots after investigating a little bit more I figured that there is one other small issue here.
When working with web-compoents all default events are being composed but the custom ones. You are using custom ones so if you want to solve this issue completely all events have to be configured with `{composed:true}` at the same level where you configure bubbles like `{bubbles:true,composed:true}`.
There is a "but" here. In one case you are using only the deprecated way to create a custom-event which does not support compose..

**Comment by RobinHerbots** [comment]
@artvel ,

Ok.

https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow
mode
A string specifying the encapsulation mode for the shadow DOM tree. This can be one of:

open: Elements of the shadow root are accessible from JavaScript outside the root, for example using Element.shadowRoot:
element.shadowRoot; // Returns a ShadowRoot obj
Copy to Clipboard
closed: Denies access to the node(s) of a closed shadow root from JavaScript outside it:
element.shadowRoot; // Returns null

That is why I stored the shadowroot.

About the composed: true.  I think the browsers who still need the "deprecated" way of custom events, don't support an shadow dom anyway.  So that is not really a problem. 

Ok send in the PR!  Thx.

**Comment by Bodrosh** [comment]
@RobinHerbots Hello, I am facing the same problem. 
I'm using VueJs with a custom root element - it creates a Shadow DOM. One of the application components contains a field for entering a phone number (with Inputmask). The caret always jumps to the end after any input.

The input.inputmask.shadowRoot option helped me, maybe this option should be added to the documentation? Thank you.

```
directives: {
        inputmask: {
            beforeMount: (el, binding) => {
                const inputs = el.getElementsByTagName('INPUT')
                const input = inputs[(inputs.length || 0) - 1]
                new Inputmask(binding.value).mask(input)
                input.inputmask.shadowRoot = document.activeElement.shadowRoot
            },
        }
    },
```
