### ISSUE TITLE
decimal + radixpoint + digits issue

### ISSUE THREAD

**Issue by gvdhoven** [RobinHerbots/Inputmask#226]
``` javascript
$(this).inputmask({
                        alias: 'decimal',
                        radixPoint: ',',
                        digits: 2
                });
```

**Comment by gvdhoven** [comment]
Crap, no preview was given. Issue is like this:
With above code; for example you have "15,00" in the field.
You double click 15 in Chrome and try to enter 16.

Expected result: you can enter 16 and cursor is before the radix point.
Actual result: after pressing the "1", 15 is replaced with 1 and the cursor moves to the right of the radixPoint.

**Comment by jhnwsk** [comment]
+1 for this. 

I love the plugin, awesome job Robin! However, the decimal points and radix dances are somewhat confusing.

**Comment by RobinHerbots** [comment]
@jhnwsk , 

Don't you like to dance??  ;-)

I will have a look at it.

**Comment by jhnwsk** [comment]
@RobinHerbots I love to dance! Especially with radix points :)

Actually I took another look at what was going on and found that my problems were mainly caused by trying to define a decimal mask like this 

`$(".mask_currency").inputmask('€ [999.999.]999,99', { numericInput: true });`

In order to achieve the optional milions. Turned out to be a bad idea because optional blocks don't work very well with numeric input I guess - they force left to right input. With `alias: 'decimal'` it's back to awesome-as-usual :)

Sorry for the commotion.

**Comment by RobinHerbots** [comment]
@jhnwsk, 

Watch issue 253 for the optionals with numericInput true.  

I did some fixes for the decimal alias.  Only setting an initial value doesn't work yet coorectly.  But I know the cause, just need some time to fix it.

**Comment by jhnwsk** [comment]
@RobinHerbots,

Thanks, I will.

**Comment by RobinHerbots** [comment]
@Webunity , 

Try again with the latest version.

I will update the nuget tomorrow.

Robin
