### ISSUE TITLE
decimal and integer does not respect placeholder

### ISSUE THREAD

**Issue by sas1973** [RobinHerbots/Inputmask#244]
The decimal and the Integer aliases does not respect the placeholder option unlike the mask option. 

This one works:
$("#FIELD_NUM_18").inputmask('9',{ placeholder: "0", clearMaskOnLostFocus: false });

This one does not work:
$("#FIELD_NUM_18").inputmask('integer', { placeholder: "0", clearMaskOnLostFocus: false });

$("#FIELD_NUM_10").inputmask('decimal', { digits: 3, placeholder: "0", clearMaskOnLostFocus: false })

Am I missing something or is this a known issue? 

Thanks

**Comment by RobinHerbots** [comment]
@sas1973 ,

This is because there is no place to hold.  The decimal and integer alias, are non-greedy, so they do not allocate elemnts if not needed.  The placeholder is used to visualize the mask.  example a mask 999 with placeholder "_" results in an empty mask of "___", or with placeholder "12" => "121" as empty mask  or placeholder = "Hello" => "Hel" as empty mask, ...

Why don't you set an initial value of 0?
