### ISSUE TITLE
Issue with cyrillic letters in iOS

### ISSUE THREAD

**Issue by narek-t** [RobinHerbots/Inputmask#2442]
On iOS devices, there is an issue when typing Cyrillic letters. Mask stops working if any Cyrillic letter was inputted. 
Here is a link with the issue https://jsfiddle.net/yvw0bude/

Any solution?

Tested on these devices:
iPhone xs  max ios 14.3
iPad mini 5 ios 14.2

**Comment by aramis-it** [comment]
Any solution?

**Comment by danitatt** [comment]
iOS 15, cyrillic not working =(

**Comment by RobinHerbots** [comment]
@danitatt , 

Is this specific to IOS or does this also occur  on android or desktop?
as info https://www.w3schools.com/charsets/ref_html_utf8.asp

**Comment by danitatt** [comment]
@RobinHerbots ,
I thins is this specific to IOS.

In inputmask@4.0.3 did not observe this problem.

I tried to find the changes that are causing this error, but I failed. Debug in ios does not give any errors.

inputmask@5 has more functionality and works more stable, I would really like to use it. But at the moment, due to problems on ios, use becomes impossible

**Comment by danitatt** [comment]
@RobinHerbots ,

here is a good example

<img src="https://i.ibb.co/XLYB2SV/ezgif-3-37c536a0e00e.gif">
