### ISSUE TITLE
Feature: autocomplete masks on tab?

### ISSUE THREAD

**Issue by gvdhoven** [RobinHerbots/Inputmask#29]
Hi Robin, its me again, sorry :)

This feature request is for both money fields and percentage fields.

As example: i have this mask:

$('#percentage').inputmask({ placeholder: ' ', 'mask': '999.99', numericInput: true });

(or)

$('#feeinputmask({ placeholder: ' ', 'mask': 'EUR 999.99', numericInput: true });
(p.s. € does not work on UTF-8, and '&#0128;' is not translated to an euro sign)

Now the question is this:
I would like that the user can enter the '.' even though the user is not on the '.' mask position. For instance instead of forcing the user to enter "0.50" i would like the user to be able to enter "0.5" and tab out of the field, which would make it "0.50".

Is this possible using a combination of "validator" and "prevalidator" ?

**Comment by RobinHerbots** [comment]
Hi Gilles,

I never have a problem with good ideas ! ;-)

I like the idea and it could and should be implemented in the
(pre)validation logic.  I am even thinking of putting all code for full
numeric support in an alias, with it's own definitions, etc (although I
don't know that is possible without changing some things in the base code)

First thing is to remove the TAB char out of the ignorables, ... otherwise
the TAB key wont trigger the validation code.

Anyway this issue is related to issue 12, ... or it will be a feature,
included in issue 12 or this feature will implement issue 12.

Robin

2012/2/20 Gilles van den Hoven <
reply@reply.github.com

**Comment by RobinHerbots** [comment]
I will implement this throught the keyup event.  In the options onKeyUp: function(e) { do something } in the alias you can override the option to implement what is needed

**Comment by RobinHerbots** [comment]
An example can be find in the decimal alias (onKeyDown)
