### ISSUE TITLE
Question: Possible to just use validation without mask functionality?

### ISSUE THREAD

**Issue by MarcDiethelm** [RobinHerbots/Inputmask#310]
Hi. Basically the title says it all. I would like to know if it's possible to disable the masking functionality alltogether and just use the validation (callbacks).

**Comment by RobinHerbots** [comment]
@MarcDiethelm , 

And what would be the use?

**Comment by MarcDiethelm** [comment]
For one thing you offer a wonderful way to define patterns for validation, that don't require writing (and testing) Regex. This is awesome and quite a time-saver. Other validation methods (libraries or not) require Regexes.

Using the input masks however is not always guaranteed to work consistently and to the satisfaction of all users. Some people simply don't like the look of it. :) So there's a reason to not want to use the masks, but still use the powerful pattern definition for validation.

**Comment by RobinHerbots** [comment]
@MarcDiethelm , 

The inputmask does not dictate that you need to apply a format..  Instead of 99-9999-99 you can also use 99999999 as mask and set the placeholder to an empty string. 

When I look at jquery.validate, you specify a function for validation.  So there is no requirement to use regexes.  

However writing a generic validator in jquery.validate (or other) which accepts the pattern definition of the inputmask would be nice.

**Comment by RobinHerbots** [comment]
@MarcDiethelm , 

Added feature in the 2.6 branch.  As soon this branch is released the feature will become available.

**Comment by MarcDiethelm** [comment]
@RobinHerbots Wow. You're awesome!
