### ISSUE TITLE
Release 2.4.18 is broken.  Malformed bower.json

### ISSUE THREAD

**Issue by beck** [RobinHerbots/Inputmask#414]
Looking at:
https://github.com/RobinHerbots/jquery.inputmask/blob/2.4.18/bower.json

The description has newlines and unescaped quotes.

Bower fails to install with:
`EMALFORMED Failed to read jquery.inputmask-2.4.18/bower.json`

Side request: keep old releases and tags for posterity? a changelog too?

**Comment by lalitkapoor** [comment]
:+1:

**Comment by imorrison** [comment]
You cannot have multiline strings in json. Also, bower expects a string below 140 characters for the description. 

From the [`bower.json specification`](https://github.com/bower/bower.json-spec/blob/master/README.md):

#### description [string]

Help users identify and search for your package with a brief description. Describe what your package does, rather than what it's made of. Will be displayed in search/lookup results on the CLI and the website that can be used to search for packages. Recommended.
- Any character. Max 140.

**Comment by tmartensen** [comment]
:+1: 
Also a :+1: for keeping older tags. That way, people can stabilize on a specific version.

**Comment by RobinHerbots** [comment]
@beck , @lalitkapoor , @imorrison , @tmartensen ,

I updated the bower.json, ... can someone verify that it works now.  Because I get bower error status code of git: 128 on my machine at work.  If someone got a quick fix for that?

I will treat the tags as real releases from now on and thus keep them available.

@imorrison , 
Thx for the link to the bower.json spec

**Comment by lalitkapoor** [comment]
@RobinHerbots looks good here.

**Comment by lalitkapoor** [comment]
@RobinHerbots for the bower error you're facing - maybe clean your cache: https://github.com/bower/bower/issues/50#issuecomment-8572614

**Comment by beck** [comment]
> I will treat the tags as real releases from now on and thus keep them available.

:+1:
