### ISSUE TITLE
Placing cursor position using mouse

### ISSUE THREAD

**Issue by blevins** [RobinHerbots/Inputmask#422]
I have a mask of {"mask": "(999) 999-9999"} for US telephone numbers. The area code is optional, so phone numbers can be entered as (___) XXX-XXXX. However I can't place the cursor past the first empty position. I can use arrow keys to get there, but this might not be obvious to users. Is there a way around this?

And thanks for all your hard work on this.

**Comment by blevins** [comment]
I'm new to this plugin, so I just realized that perhaps I need to set the mask to {"mask": "([999]) 999-9999"} instead. But the cursor will not skip the optional chars (using a mouse).

**Comment by RobinHerbots** [comment]
@blevins, 

The caret jumps to the first unmasked position to aid in the input.

Your case is a bit strange as you want masking but also want a portion optional but still visible.

At first thought it would be "[(999) ]999-9999" making the first part optional.  But how can we determine what the user wants when the input is valid for the 2 cases.  see http://jsfiddle.net/bMwTP/

Another thought instead of making the area optional, ... can't you set a default?

**Comment by blevins** [comment]
@RobinHerbots 
Thanks for the prompt response. I think setting a default might be the way to go in this case.
