### ISSUE TITLE
Decimal mask doesnt have the "oncomplete" concept

### ISSUE THREAD

**Issue by YoussefTaghlabi** [RobinHerbots/Inputmask#447]
Consider the following scenario using the following configuration in v2.5.4:

```
$(<SELECTOR>).inputmask("decimal", { 
    radixPoint: ".", 
    groupSeparator: ",",
    groupSize: 3,
    digits: 2,
    autoGroup: true,
    placeholder: "0",
    oncomplete: function(){
        console.log( "oncomplete done" )
    }
});
```

The oncomplete doesnt fire for the `decimal` mask because it can have an x amount of characters.

Ideally, the `oncomplete` function should fire once the user blurs out from the input, and the input value is valid.

![foo](https://f.cloud.github.com/assets/1639024/2360560/e7097fac-a625-11e3-92c9-7bf57a59b407.png)

**Comment by RobinHerbots** [comment]
@YoussefTaghlabi , 

That is because the repeat in decimal alias is \* by default, so it cannot determine when the mask is complete.  \* is infinite.

Anyway I added an override or call-in.  isComplete option.  With this you can override the functionality of the isComplete function with your own logic to verify completeness.  

I will add this to the numeric extension soon.
