### ISSUE TITLE
Remove on input.blur is not working (version 2.5 from NuGet)

### ISSUE THREAD

**Issue by j-morgan** [RobinHerbots/Inputmask#475]
Hello,

I am working on an application where the user would like to see a placeholder (in place of using any labels) to tell the user what the field is for.  When I use the inputmask, that placeholder goes away.  So I have tried to add a mask on input.focus and then remove the mask on input.blur.

```
            input.focus(function () {
                $(this).inputmask('9999');
            });

            input.blur(function () {
                $(this).inputmask('remove');
            });
```

I am getting an error when the input.blur is fired.

TypeError: input._valueGet is not a function

On this line:

 }).bind("blur.inputmask", function () {
var $input = $(this), input = this, nptValue = input._valueGet(), buffer = getActiveBuffer(); 

I saw other issues that said this was resolved in earlier versions, but I still have this problem.

**Comment by RobinHerbots** [comment]
@j-morgan , 

Can you create a jsfiddle with the placeholder not showing in combination with the inputmask
I feel more like fixing that first.

best regards, 
Robin

**Comment by rteegarden** [comment]
So this issue is very similar to mine and the answer here will be the end of that one. (https://github.com/RobinHerbots/jquery.inputmask/issues/524). I have made a couple jsfiddles
1. http://jsfiddle.net/rx8eQ/1/  This is the error he described with the problem with the input._valueGet() call
2. http://jsfiddle.net/rx8eQ/3/  This is an example using autoUnmask, but the value is not there.

I am trying to solve the same issue, I want the unmasked value passed into my MVC controller.  I am not particular how it gets done.

TIA!

**Comment by RobinHerbots** [comment]
@rteegarden, 

First issue is fixed.

I will have a look at the unmaskedvalue.

**Comment by RobinHerbots** [comment]
unmaskedvalue fixed

**Comment by rteegarden** [comment]
Thank you!
