### ISSUE TITLE
Create the master branch

### ISSUE THREAD

**Issue by thiagotalma** [RobinHerbots/Inputmask#481]
Hello! 
It would be great if you created the master branch with the most current version of the project. 

I was watching the 2.x branch had not even realized that there was already 3.x. 

If there was the master branch, this problem does not occur.

**Comment by RobinHerbots** [comment]
@thiagotalma , 

This is just a transition period.  I only have time to maintain one branch. And branch 3.x is born because the implementation of dynamic masks has progressed enough.

I will soon abandon branch 2.x, but for now I still accept patches for it.  The default selected branch is considered the master.   So now it is already 3.x
