### ISSUE TITLE
How to get unmask value in MVC controller (int)

### ISSUE THREAD

**Issue by rteegarden** [RobinHerbots/Inputmask#524]
So basically the same question as this post: http://stackoverflow.com/questions/21637938/how-to-get-unmask-value-in-mvc-controller

Only difference for me, is my data type is an int, so when my controller ActionResult is called, the SSN number is already 0 - since it is not a string.  I don't even have the option to do: Model.SSN.Replace('-','')  

I am adding to the page like:
$("#EmployeeSSN").inputmask({ mask: "999-99-9999", autoUnmask: true });

The unmasked value is not getting passed through to the ActionResult call.

**Comment by RobinHerbots** [comment]
The problem is that not all browsers support patching the native value
property and thus not calling the unmasking.  Firefox allows that.

What can be done.  Post your forms through AJAX, and build your submit data
yourself. (and call the unmasking)

or bind to the form submit event and replace the values with the unmasked
ones.

BUT, .... i will try to find a solution out of the box.

2014-05-13 8:21 GMT+02:00 Rob Teegarden notifications@github.com:

**Comment by rteegarden** [comment]
OK, for now I will just use the solution provided in https://github.com/RobinHerbots/jquery.inputmask/issues/475

Thank you

**Comment by RobinHerbots** [comment]
You can now use the removeMaskOnSubmit option.
