### ISSUE TITLE
IE8 - Multiple Masks Error

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#539]
Hi Robin!

I'm getting a error on IE8 only with Multiple Masks, error description:
Object doesn't support this property or method 'indexOf'

``` javascipt
// Line 1592
if (["click"].indexOf(e.type) != -1) {
    mcaret(lmnt, TranslatePosition(caretPos.begin), TranslatePosition(caretPos.end));
    if (caretPos.begin != caretPos.end) {
        goDetermine = false;
        return;
    }
}
```

Mask:
 $(selector).inputmask({ mask: ["999.999", "aa-aa-aa"]});

Great feature BTW!!

**Comment by RobinHerbots** [comment]
@spacelab-x , 

Can you have a try in IE8

**Comment by spacelab-sp** [comment]
Hi Robin! Now it is giving another error in any browser. Only with Multiple Masks.

// Line 258 -  function getMaskTemplate
**if (baseOnInput === true && getMaskSet()['validPositions'][pos]) {**

Error:
Uncaught TypeError: Cannot read property '0' of undefined

**Comment by RobinHerbots** [comment]
@spacelab-x , 

Did you include the jquery.inputmask-multi.js?  or are you using the bundle?

**Comment by burreld** [comment]
IE8 also has issues with the use of indexof.  I made manual changes to use the $.inArray and this seemed to fix the issue. Do you want me to some how submit the changes we made?  I am not sure how

**Comment by spacelab-sp** [comment]
@RobinHerbots This source: https://raw.githubusercontent.com/RobinHerbots/jquery.inputmask/3.x/js/jquery.inputmask.js

**Comment by RobinHerbots** [comment]
@burreld , 

Thx, but I already replacedx the indexof for array to inArray.

@spacelab-x, 

I've moved the multiple-mask implementation in a separate file which you have to include as an extra to make the multi-masks work.  include the jquery.inputmask-multi.js.

Anyway I will adapt the jquery.inputmask.js so that it does not fail when using multipla masks without the jquery.inputmask-multi.js ,but just uses the first mask.

In the future this will all ge away when I implemented the alternator syntax, which will replace the current multi-mask implementation.

I will update the readme

**Comment by spacelab-sp** [comment]
@RobinHerbots Worked! Thanks
