### ISSUE TITLE
inputmask, date.extensions and JSON

### ISSUE THREAD

**Issue by gjdevlin** [RobinHerbots/Inputmask#575]
So far I got the inputmask (3.055.js) version working great along with the inputmask.date.extensions.

The problem is that when I populate the form fields with json data loadJSON(jsondata) the textbox inputs that contain the masks do not get populated with the json data.

I removed the .inputmask in the DOM loading and I was able to loadJSON into the HTML.

Is there away around this so that I can have the data come back from JSON and preserve the functionality of the inputmask?

**Comment by gjdevlin** [comment]
I think you can close this. I was forced to use $('#textboxFollowupdate').val(result.d.followupdate) for each date field that implements your plugin.

I really wanted to to use the loadJSON(jsonData) to make things faster when binding.

**Comment by RobinHerbots** [comment]
@gjdevlin , 

Is this the site of loadJSON https://code.google.com/p/jquery-load-json/ ?
The problem is that the native value property cannot be patched on most browsers.  So the inputmask isn't aware of the value change.  
When you call $(":input").trigger("setvalue"); after the loadJSON it should work.

Can you try?

**Comment by gjdevlin** [comment]
Hi Robin - yes that is the site of the loadJSON()

The above suggestion did not work though. thanks for trying.
