### ISSUE TITLE
Hover/Mouseover causes value to disappear

### ISSUE THREAD

**Issue by rjryerson** [RobinHerbots/Inputmask#585]
I have a textbox with knockout and when I implement inputmask, it causes the text/value to blankout. 

here is a fiddle that reproduces the behavior. 

http://jsfiddle.net/rryerson/sPa9K/

Thanks for looking into this, Rick.

**Comment by navnitmehta** [comment]
See issue #559, I had a similar issue and I worked around it by creating a proxy binding until correct fix is found.

**Comment by RobinHerbots** [comment]
@rjryerson , 

Fixed in the latest version.

I use some kind of fallback which is not perfect but will do in most cases.

In FF it will be perfect.  In chrome and ie it will pick up the value set by the native value property on mouseover.  

Best choice is using jquery.val which will work equal in all browsers
