### ISSUE TITLE
Auto populate with current month and year 

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#610]
There is a requirement while entering the date field. Like if i enter 20 and tab out, then the current month and year should be auto populated.

dd-mm-yyyy  = 20-mm-yyyy (here month and year should be autopopulated. With the latest 3.60 release is there any way to achieve this requirement.
## jsfiddle link

http://jsfiddle.net/BA251281/90fmzL7f/4/

**Comment by RobinHerbots** [comment]
@babupca , 

You can find an example in de numeric extension and use the same  but for the date extension.

onKeyDown option

**Comment by mouratos66** [comment]
Hello,
I think that this kind of feature should be switchable (maybe through use of a flag?)  and IMHO all such extensions should be switchable (for example, typing 4444 on a field with "date" input mask, would result to a date of 04/04/2044, but such functionality should be enabled on request and not automatically).

Is there something that can be done on this matter ?

Thanks for your excellent work and best regards

FF

**Comment by RobinHerbots** [comment]
@mouratos66 , 

Nothing prevents you from not using the date alias and just use 99/99/9999 as mask or d/m/y.
I don't now about the 4444.  What should you prever as result in that case?

**Comment by mouratos66** [comment]
In the former case, if one uses 99/99/9999 the date validations will have to be manually performed. 

In the case of 4444, in my opinion, there should be a flag forcing the input to be exact, i.e. for a "date" (which if I am not mistaken is an alias of "dd/mm/yyyy" anyway) the input should forcibly be 04042044 unless a "shorthand" flag is enabled (to permit typing 4444 and getting 04/04/2044).

This way one can get the best of both worlds. Strict(exact) by default, fluent / fast typed when required. or specified...

**Comment by RobinHerbots** [comment]
@mouratos66 , 

Hmm, yes, ... I can understand want you mean.  Just curious, do you have a real use case currently that requires the "strict" mode?

I'm planning to review (rewrite) the date aliases, So depending if your need is now I can add a quickfix or otherwise wait until the refactoring.

**Comment by mouratos66** [comment]
Robin, in fact I do have the business people nagging me about this because their data entry people complained that there were (thankfully not that many) cases when they input the wrong thing (especially when inadvertently pressing the "3" numeric key twice without noticing).

Insofar as development cycles go though, I leave it entirely up to you. It would be helpful to have it sooner rather than later, but I will not lose my sleep over it in case I don't ...

Thanks again for the brilliant work and swift responses
Best Regards

Philip

Edit: They told me it is the number "3" key and not "1" as I thought...
