### ISSUE TITLE
knockoutjs & inputmask issue

### ISSUE THREAD

**Issue by RobinHerbots** [RobinHerbots/Inputmask#63]
Is there a way I could use knockoutjs with your pluggin and also have the options of 'autoUnmask': true, clearMaskOnLostFocus: true?

For some reason, if I have these set to true with knockoutjs also binding to the same fields then when I mouse over the fields it will clear the input values along w/ the mask.

**Comment by RobinHerbots** [comment]
Hi Evan,

Can you send an sample so I can verify the issue.

Best regards,

Robin
SEE ISSUE 53

**Comment by evanlarsen** [comment]
Sorry for the delay, i havent checked github in a few days, I'll provide an example tonight

**Comment by evanlarsen** [comment]
Well, I cant recreate the problem, in fiddle.. I tried my best to re-create it in jsfiddle but it seems to work in fiddle but doesnt work in my site.

I cant see any difference.. but I'll keep looking.  I get a strange behavior when I hover over the phone numbers it will erase the input if there is any.  I have to specifically set autounmask to false so that it wont erase whats already in there.

Here is the jsFiddle of what I have so far.
http://jsfiddle.net/evanlarsen/8vnP3/

I can describe whats happening, I'm not sure if this will help.
So, If I have autoUnmask = true and clearMaskOnLostFocus = true.  Then when I click and drag one of the phone numbers to a difference sequence and then hover over the phone number textbox and then move my mouse out from it, inputmask will remove the phone number and the mask.  Clearing the values from the textbox.  I have to set autoUnmask and clearMaskOnLostFocus to false in order for it to not clear out the phone number on mouse over -> out.

**Comment by evanlarsen** [comment]
Actually, I just updated to your latest version and its working good now.  Not sure what changes you made but it fixed my problem.

Thank you!

**Comment by RobinHerbots** [comment]
Probably it was related to issue 74
