### ISSUE TITLE
Cannot delete phone number extension, cannot replace characters in input field

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#649]
On Mac Safari ( 7.0.6 ), Chrome 37.0.2062.94, Ubuntu FF 31.0 .
On your demo webpage : http://robinherbots.github.io/jquery.inputmask/ 
when I enter phone number i.e. 44444444444 ,then try to delete that and I cannot delete first 2 numbers. 

Second issue ( i think ) - why it’s not possible to overwrite/replace input text? - if I made a mistake somewhere in the beginning of the input I need to backspace delete everything and then correct single character

**Comment by RobinHerbots** [comment]
@jbernatowicz, 

For the second issue you can press the insert on your keyboard to switch from insert mode to overwrite mode like you have in other editors.

For the first, ... this is due to the maskdefinitions in the phone-codes.js.  You do not have to delete the extension, just start typing.  Anyway the phone alias needs some tuning and extra work, I will fix delete of the extension when I find some time.

**Comment by ghost** [comment]
For the second .. I'm Mac user since a week, and I don't know where's the insert key, if I don't I assume other users can have the same problem and I need my app to be as user friendly as possible. 
Is there a way to enable character overwrite in inputmask by default ?

I also think I've found another issue : I couldn't use backspace at all - after investigating I realized that it's not compatibile with https://github.com/jeresig/jquery.hotkeys I've been using in my project.

**Comment by RobinHerbots** [comment]
@jbernatowicz , 

Yes you can set the insertMode: false option.

For jquery.hotkeys, ... can you verify wheter the backspace raises a keydown event and which keycode does it send?

**Comment by ghost** [comment]
keycode : 8

**Comment by RobinHerbots** [comment]
Can you make a jsfiddle with a demo

**Comment by RobinHerbots** [comment]
@jbernatowicz , 

This is fixed in the latest commit.

**Comment by ichepurnoy** [comment]
Dear @RobinHerbots , I'm experiencing some similar issues with masking a 'phone' field (on both my website and your demo)

Let's say, I type in '+380(50)111-22-33'  (let's imaginary alias these digits as '+abc(de)-fgh-ij-kl'  )
Issues fall into 2 categories:
1) **AR** (achieved result): When deleting 'h' in a mask, _the digits are shifted to the left_, like  '+abc(de)-fgi-jk-l_'
The user is unable to insert any digit, unless the cursor is positioned before letter 'j', i.e. before last group preceded by a hyphen.
N.B.:  I've noticed that on the 'License plate' example on your Demo page, a user can insert symbols anywhere, although, when deleting,  the symbols are shifted left as well.
**ER** (expected result): When deleting 'h', a placeholder shows through, like, for example, '+abc(de)-fg_-ij-kl'. Thus giving the user a chance to insert a correct digit.
_#1 is way more important than #2._

2) InsertMode is flawed, anywhere: when using it, typing is stuck as soon as we hit non-digits (hyphen or parens). **AR**: we are stuck. unless we type in a hyphen, or a paren.
**ER**: we jump over a hyphen/paren and continue.

Is it fixed by adjusting some config options?  If not, can I help you somehow on fixing this?  Thank you in advance!
