### ISSUE TITLE
Side Effect while typing with input mask.

### ISSUE THREAD

**Issue by FakeArShui** [RobinHerbots/Inputmask#7]
suppose I have applied an input mask "9999-mm-dd" associated with a textbox (whose value is 1901-12-30).  While the cursor is not at the end of the input mask, typing every valid character cause existing input shift to the right (unless I manually select one character)

i.e. if the caret position is at 0 (i.e. before 0) when I type 2, the resulting input become 2190-11-23 (instead it should become 2901-12-30).

This behavior is not desired for input mask with a fixed length.

http://www.examplet.buss.hk/jquery/caret.php jQuery addon for tracing caret position

Please fix it

**Comment by RobinHerbots** [comment]
Hmm, I don't know.  It's the default behavior of in input control. 

Why do you have a problem with the default behavior, when the input is used with a mask?

Maybe I can add it as an option?

**Comment by FakeArShui** [comment]
I know this is the default behavior, but it doesn't applied to the concept of input mask, especially the input field is having a fixed or contains of several part.

This is because the concept of input mask is to apply some kind of restriction to the valid character being typed by the user, so allowing the default behavior may not be suitable.

Please Take A Look at http://www.asp.net/ajax/ajaxcontroltoolkit/Samples/MaskedEdit/MaskedEdit.aspx, and try yourself regarding date or time.

This is OK to treat it as an option.

**Comment by RobinHerbots** [comment]
Ok, version 0.3.3 contains a new option insertMode who fixes this.

Should the cursor be visible different?

**Comment by dmaii** [comment]
Hi Robin,

Thanks for all the great work you've done on this plugin. I have a request to make with regard to this closed issue.I'm not sure if this should be a new issue or a modification to an existing one, so I'm keeping it in this same issue since it's the same topic.

Question:
Is it possible to add an option for insertMode, so if insertMode is true, and the user's input has reached the max length of the field, prevent the user from entering in additional characters.

Example:
http://jsfiddle.net/7AJTD/3/

On the first field in Result, Mask is ###-##, user entered 123-45.

Current: If the user moves the caret to the beginning of the field, and types 9, then the field becomes 912-34.The 5 at the end is pushed off of the field.

My Request: If the user moves the caret to the beginning of the field, and types 9, then nothing happens. 

Reason:

The reason for my request is that this would keep the same behavior that basic HTML inputs allow. For example, on the same jsfiddle: http://jsfiddle.net/7AJTD/3/ , on the second field:

There is no masking, and the default value is 12345. If you move the caret to the beginning of the field, and type 9, nothing will happen. Is it possible to have an option that can simulate this behavior?

**Comment by RobinHerbots** [comment]
Hi DM, 

I don't think it should be an option, it should just be the behavior.  I will fix this soon.

Best regards, 

Robin

**Comment by RobinHerbots** [comment]
check out the latest of the dev branch.
