### ISSUE TITLE
Phone Extension edit

### ISSUE THREAD

**Issue by BesedinSasha** [RobinHerbots/Inputmask#706]
When input, for example, +380(50)555-66-77
when move cursor between phone number digits and try to enter digit, phone breaks (e.g +381-66-077-____)

**Comment by ichepurnoy** [comment]
Dear @RobinHerbots , I'm experiencing some similar issues with masking a 'phone' field (on both my website and your demo)

Let's say, I type in '+380(50)111-22-33' (let's imaginary alias these digits as '+abc(de)-fgh-ij-kl' )
Issues are as follows:
1) AR (achieved result): When deleting 'h' in a mask, the digits are shifted to the left, like '+abc(de)-fgi-jk-l_'.
The user is unable to insert any digit, unless the cursor is positioned in '-kl' group of symbols.
N.B.: I've noticed that on the 'License plate' example on your Demo page, a user can insert symbols anywhere, although, when deleting, the symbols are shifted left as well.
ER (expected result): When deleting 'h', a placeholder shows through, like, for example, '+abc(de)-fg_-ij-kl'. Thus giving the user a chance to insert a correct digit.
(1) is way-way more important than (2) or (3). 

2) ~~**AR:** When phone field gets focus on Tab, the mask gets selected, like when Ctrl+A is pressed
**ER:**  the cursor is set to the beginning of a mask, just like when clicking the field.~~ 
Was able to fix it by `positionCaretOnTab : true` :)

3) InsertMode has a bug: when using it, the typing is stuck as soon as we hit non-digits (hyphen or parens). AR: we are stuck. unless we type in a hyphen, or a paren.
ER: we jump over a hyphen/paren and continue.

Is it fixed by adjusting some config options? If not, can I help you somehow on fixing this? Thank you in advance!

**Comment by ichepurnoy** [comment]
Maybe this can be fixed by using options like  `skipOptionalPartCharacter, definitions, ignorables`. But they are all unclearly defined in the docs.
Ideally, the issue would be solved if either:
1) Delete / backspace leaves an empty space, without shifting characters.
2) or, if using InsertMode, cursor jumps over parens and hyphens. I'd need to block 'Delete' and 'Backspace' then.

**Comment by RobinHerbots** [comment]
@Besedin86 , @ichepurnoy ,

The current version on github resolves this.
