### ISSUE TITLE
On Tabbing digit value is also getting replaced 

### ISSUE THREAD

**Issue by babupca** [RobinHerbots/Inputmask#723]
JSFIDDLE LINK
http://jsfiddle.net/BA251281/ug16s3tw/14/

Decimal mask with 6.3 -  integerDigits:6, digits:3 

Step 1: type in Field One at jsfiddle like this  -    123456.789
Step 2: now place the cursor before the radixpoint  123456(cursor here ).789 and press the BACKSPACE
Step 3: now you can notice like this result -  000000789
Step 4: now beign in this field, press SHIFT + TAB to "field zero" in jsfiddle and again TAB to the "field one" in jsfiddle
Step 5: Now the "field one" beign SELECTED, press 1, 
Setp 6: The result is below   -   100000.0900

123456.789
123456.789 (put cursor before radixpoint 123456(cursor here).789 and keep pressing BACKSPACE
000000789 - now shift+ tab to the previous field and again come back to this field and content beign selected, press one

RESULT is coming as --    100000.0900 

---

Decimal mask with 5.2  ( integerDigits:5,  digits:2) 
Again please try the same way for this mask also

12345.67
0000067 - now shift + tab and again come to the same field and press 1
RESULT 10000.08
The result is wrong (which should be 1.00)

---

**Comment by babupca** [comment]
@RobinHerbots, 

Please note, this issue is related to the  #722

**Comment by RobinHerbots** [comment]
@babupca , 

I cannot reproduce ;-(  
Can someone else confirm the problem.

**Comment by babupca** [comment]
@RobinHerbots 

I use the windows 7, chrome and the latest version. 

I have the .webm deomo file. And attached that to you. Since git does not supprt the .webm file, i just changed the format to gif. You can change this again to .webm file and check the demo.

![decimal mask issue demo](https://cloud.githubusercontent.com/assets/2504343/4952729/5285c994-6678-11e4-8e1c-fe0e496d662d.gif)

**Comment by laxmikantG** [comment]
@RobinHerbots/@babupca :-    Tried in ubuntu, but not reproducible. Will try in windows next time.
Our testing team also have found a similar kind of issue. Please check following screen grabs. 
But they do use Air Client on windows instead of chrome. It happens on pressing backspace only

![screen_grab1](https://cloud.githubusercontent.com/assets/1826523/5042265/2ff8330a-6bf8-11e4-9217-7b4d7d0f6cb8.png)

![screen_grab2](https://cloud.githubusercontent.com/assets/1826523/5042257/11bee9ce-6bf8-11e4-909e-2c4bda3c7eb3.png)

**Comment by babupca** [comment]
@RobinHerbots ,

This issue is fixed Now. Thanks
