### ISSUE TITLE
regex not working

### ISSUE THREAD

**Issue by oroalej** [RobinHerbots/Inputmask#764]
the example in the documentation is not working. i already did the data-inputmask-regex="" and (select).inputmask('Regex'); but still not working. i also try the (select).inputmask('Regex'{regex: ""}); but still not working. can someone help me.thanks

**Comment by RobinHerbots** [comment]
@oroalej , 

Did it work out? 

Any suggestion to update the readme?

**Comment by oroalej** [comment]
I just use the jquery.inputmask.bundle.min.js instead of jquery.inputmask.js

**Comment by oroalej** [comment]
@RobinHerbots. i have a question
i have this input mask.. mask: '99-999-999';
when the user input less than 8 numbers and focusout the textbox. the value will vanish. how can i fix this??

**Comment by RobinHerbots** [comment]
Can you give some additional info because that is unexpected.

**Comment by RobinHerbots** [comment]
@oroalej , 

Did you specify the clearincomplete option?

Otherwise see http://jsfiddle.net/sefhsoqd/2/

**Comment by AStoker** [comment]
I am experiencing another issue with regular expressions. It appears that the regex input mask does not constrain properly. Basic example: 
http://jsfiddle.net/theandybob/cpct35h2/

The issue happens when you try to exceed the initial limit on numbers left of the decimal. The regex identifies the string as invalid, but the input mask thinks it's okay. Additionally, you can type at least 1 character into the input mask, even though our regex is only for numbers.

**Comment by AmaliDeveloper** [comment]
Hey you can get the solution for this problem here Good Work [Link](https://youtu.be/dV3s7s_8fnE)

**Comment by RobinHerbots** [comment]
?

**Comment by RobinHerbots** [comment]
@AStoker , 

I don't know if it is still relevant, but have a look at http://jsfiddle.net/cpct35h2/459/

**Comment by AStoker** [comment]
@RobinHerbots, this is digging way back for me 😛 I don't even recall the exact issue we were experiencing. Sooooo, I'm just gonna say good work, thanks for fixing it!
