### ISSUE TITLE
change event not firing

### ISSUE THREAD

**Issue by ThomStilwill** [RobinHerbots/Inputmask#785]
I am using version 3.1.44.  I am finding that the change event is not firing on my masked fields.

$(".decimal-mask").inputmask("decimal", { greedy: true, digits: 2 });
$(".int-mask").inputmask("integer", { greedy: true });

$("#someinput").on('change',function(){
    console.log('this will never happen.');
});

Any ideas?

**Comment by RobinHerbots** [comment]
It should trigger change on blur.
I will have a look at it

**Comment by ThomStilwill** [comment]
blur is fired, but not change.

Thom

Thom Stilwill

**Comment by RobinHerbots** [comment]
@ThomStilwill , 

I did a quick test in the latest version. And the change was fired on blur.  Can you confirm.

```
 $("#test3").inputmask("integer");
            $("#test3").change(function(e) {
                alert("there was a change");
            });
```

**Comment by nathanzirpl** [comment]
Hi Robin, unfortunately this is still not working. Please see attached example with the lastest 3.x code (I grabbed from github rather than nuget to make sure I had the latest). We would love to get this working. 

Thanks
Nathan

I could not attach the example and can't find your email. Email me at Nathan.LaFratta@numotion.com.

Thanks

**Comment by RobinHerbots** [comment]
@zirplsoftware , 

Have a look at http://jsfiddle.net/70jp96nd/1/

**Comment by ThomStilwill** [comment]
Robin,

We found a very obscure bit of code on our end that was causing the
trouble.  It took 6 eyes and many hours but we did it.  Thanks for the help
and we love your product.

Regards,

Thom Stilwill

Thom Stilwill

**Comment by gaetanosestito** [comment]
Hi,
it seems that type="text" in input doesn't fire change event when use bootstrap.
<input type="text" class="form-control text-uppercase text-center" id="myID" placeholder="myIDph" >
if I remove type="text" change event fires well!!!

gaetano

**Comment by robertuniqid** [comment]
I don't know if I should "revive" this, but a different case where the .change event doesn't fire, is when for example on the percentage field type, the default value is 0%, and I want to set it to 0%.
I'm looking into a solution right now, I've been thinking on the approach, and I think if I set it to " 0%" when inside the placeholder instead of "0%" it will properly detect the change.

Or maybe I will just use "%" as the placeholder instead of a zero.

Hopefully this helps.
