### ISSUE TITLE
phone alias => autoUnmask should include country code

### ISSUE THREAD

**Issue by sameness** [RobinHerbots/Inputmask#800]
Hi there!

I use autoUnmask flag and everything's good but how can I get a country code value?

**Comment by RobinHerbots** [comment]
Is this about the phone alias?

**Comment by sameness** [comment]
Yes, you're right.

**Comment by RobinHerbots** [comment]
What do you mean exactly?   The country code is missing from the unmaskedvalue?

**Comment by sameness** [comment]
yes, if I enter 7 (913) 812-45-15 where "7" is country code then unmaskedvalue will be 9138124515.

**Comment by a13x3y** [comment]
maybe your mask is incorrect?
with this mask : +7 (999) 999-9999 you get only 10 digits (without 7)
with this mask: +9 (999) 999-9999 you get 11 digits (with any country code)
i checked, autoUnmask works fine.

**Comment by RobinHerbots** [comment]
@sameness , 

The behavior is correct technically spoken, as an unmasked value is the value without the masking.  The 7 is seen as part of the placeholder.

But this can be solved in the onUnmask function.  

How do you use the phone alias?

**Comment by ichepurnoy** [comment]
Dear @RobinHerbots , same question: how do I get full phone number (including country code) via onUnmask?
I have my number stripped, +380(44)555-55-55 becomes 445555555.

**Comment by RobinHerbots** [comment]
In the onunmask you can alter the unmaskedvalue.  Just readd the country
prefix and return the value

Op 16:31 ZA 16 Jan 2016 schreef ichepurnoy notifications@github.com:

**Comment by ichepurnoy** [comment]
@RobinHerbots,

1)  exactly this is the problem here: how do I access this country prefix?  I can use Regexp,  but is there some internal method/way in Inputmask ?  

2) how can I mask a string value (kind of, opposite of unmask() )? I'd expect something that looks like "+380441112233".mask(). Is there any?

I'm working on validating phone via Knockout.validation, but internally using validation of Inputmask (since ko.validation does not have that 'multiple masks' feature). 
Maybe I've gone the wrong way completely, feel free to criticize me :)
Still here's my fiddle , kind of working (but ~CPU intensive) : 
[fiddle](https://jsfiddle.net/ichepurnoy/5zy10bsL/14/) 

BTW, FYI, jsfiddle no longer accepts 'External resources' from Github, only from CDNs. 

I'd like to share this integration for documentation, when/if I get it working 100%,  and if you will not mind.

**Comment by RobinHerbots** [comment]
https://jsfiddle.net/5zy10bsL/15/

Just updated inputmask ref

**Comment by ichepurnoy** [comment]
@RobinHerbots  Ok, glad to see that it does work! Maybe Github had updated URL for accessing a lib.. Still, ~80% fiddles (older that 1-2 years) that I come across, they don't work  until I update the reference to libs.

Can you pls suggest an answer to  (1) how do I access this country prefix, from inside onUnMask function, and (2) can I mask a string value?

Dear Robin, BTW, wow, your fiddle with Inputmask 3.2.6-31 is far less greedy on CPU, compared to my fiddle with versions 3.2.5 or 3.2.6-24 !  You must have optimized something in the lib. 
Pls, see [fiddle#17](https://jsfiddle.net/ichepurnoy/5zy10bsL/17/) I quickly added a country flag, just for fun. 
If you think this could be useful for your Docs, feel free to use it.

**Comment by RobinHerbots** [comment]
@ichepurnoy , 

Yes I added some caching ;-)  The country flag is a nice addition, ... maybe I can add that to the demo page.

question 1: https://github.com/RobinHerbots/jquery.inputmask#onunmask
The onunmask has the masked value and the unmasked value as arguments.  You can strip the country prefix from there.  I know this is not perfect.  But for the inputmask the phone-codes are just a bunch of masks.  Another approach  would be adding the country prefix in the metadata.  This can then be access through the getmetadata.

question 2:  see https://github.com/RobinHerbots/jquery.inputmask#format

Btw any suggestion to improve/extend  the phone alias are welcome.

**Comment by ichepurnoy** [comment]
@RobinHerbots Thank you! Pls note that a few flags (like USA , Canada, United Kingdom ) do not work. Simply because of the difference in codes. That is /easily corrected manually (either in flags codes, or your phone-codes), if you are going to add that to your Demo.  This could count as a suggestion!)

**Comment by ichepurnoy** [comment]
New suggestions:
1) to onBeforeMask function.
consider wiping out '00' in the beginning, or spaces and dashes inside the number. I've seen UK numbers written like '0044whatever'.

I did it like  **_var processedValue = value.replace(/^0{1,2}/g, "").replace(/[-\s]/g, "")**_

2) On pasting a number, my fiddle does not show country. Shows only on typing. Dont know if I'm to blame, or the lib.  
3) just a note really, I kind of cached **_maskList**_ and Ajax call in my fiddle.  I decided to, because fiddle would generate Ajax calls to phone-codes.js on every keydown. Now,  only one Ajax call. Without knockout it worked okay anyway. With KO, I had to do the trick.
Somehow, the problem did not appear on my server, maybe because of your added caching!

And thanks again! Link #2 did it for me!  :)
My situation was (may be useful for others) , that on Submit I was unmasking the phone , and sending to server. Like '+380441112233'. Then on a page reload, the server would send this back to front, and the unmasked value would fail validation. I had to just mask the string value.
https://jsfiddle.net/ichepurnoy/5zy10bsL/18/

**Comment by ichepurnoy** [comment]
@RobinHerbots I 've added this integration to Wiki, pls see https://github.com/RobinHerbots/jquery.inputmask/wiki/HOWTO:-integration-with-Knockout-Validation-plugin

**Comment by RobinHerbots** [comment]
@ichepurnoy , 

Many thx!  Really appreciated!  

and I will add your suggestions on the todo list ;-)
best regards, 
Robin

**Comment by ichepurnoy** [comment]
Glad to be of any help to you, @RobinHerbots, 
best regards,
Ilya

**Comment by Soul-git** [comment]
Not correctly identify the country of masks .
Example:
Russia - Kazakhstan ;
USA - Saint Lucia ...

**Comment by ichepurnoy** [comment]
I actually mentioned this here and in the fiddle, that flags/countries do not always work 100%.
As far as I see it, it's because (1) my example was a quick and dirty showcase, far from being polished, and (2) historically, the phone codes are such, that existing logic in Inputmask fails to distinguish them.
Kazakhstan = +7(7##)###-##-##" or +7(6##)###-##-##", while
Russia = +7(###)###-##-##". 
@Soul-git, you would need to update function **_onKeyValidation**_ from my fiddle with some Regexp, that can tell Kazakhstan from Russia, Canada from USA, etc. 
Or add some option, that tells 'start detecting country only from Nth digit, or from country code + 1 or 2 digits, just to include these 'Kz-Ru' cases

**Comment by RobinHerbots** [comment]
@Soul-git , @ichepurnoy , 

Always feel free to add/update the phone-codes.js.

**Comment by ichepurnoy** [comment]
@RobinHerbots ok, we will!  I guess the masks are more or less correct (I haven't checked though). 
The problem is, some country codes are a bit non-standard. Don't know which codes exactly: yours , or flag codes. I guess, its flag codes. Example: they are using GB for United Kingdom, while UK is more accepted, AFAIK. I'll be looking into this in a week, and post my thoughts here. 
Robin, have you seen that some countries  (like US) have "cc":["US","CA"], i.e country code as an Array. 
Does your plugin correctly get **_cc**_ if it is an Array (somehow at least, like Array[0]) ? 
If yes, then I could update codes for UK as  "cc":["UK","GB"].
If no , then maybe I better bother the author of css-flag on this.

**Comment by RobinHerbots** [comment]
@ichepurnoy , 

Normally the cc should pass the full array

**Comment by ichepurnoy** [comment]
@RobinHerbots  BTW, Robin, the link to Inputmask library that you had inserted into my Jsfiddle, is now invalid.
[https://rawgit.com/RobinHerbots/jquery.inputmask/3.x/dist/jquery.inputmask.bundle.js](https://rawgit.com/RobinHerbots/jquery.inputmask/3.x/dist/jquery.inputmask.bundle.js)
Don't know what happened, but that is why I prefer links from CDNs over links from Git.
CDNs seem to be more reliable:
[https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.2.7/jquery.inputmask.bundle.min.js](https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.2.7/jquery.inputmask.bundle.min.js)
 I will update the fiddle and the Docs.

**Comment by RobinHerbots** [comment]
Remove Phone alias #1981

**Comment by KA24956T** [comment]
how to use phone mask with extended alias of phone codes?
Please give some example.
thank you.

**Comment by nzvtrk** [comment]
working example


```const phoneInput = document.querySelector('#phoneNumber');
const phonemask = new Inputmask('+48 999 999 999', {
  placeholder: '',
  autoUnmask: true,
  onUnMask(maskedValue, unmaskedValue) {
    const [countryMask] = maskedValue.split(' ');
    return `${countryMask}${unmaskedValue}`;
  },
});
phonemask.mask(phoneInput);
```
