### ISSUE TITLE
Input mask can't be applied on other HTML5 input types

### ISSUE THREAD

**Issue by matthew-dean** [RobinHerbots/Inputmask#828]
This confused me for a while. I was trying to attach a numeric mask on an `<input type="number" />` element. No matter what I did, the input mask wouldn't apply. I finally figured out that the library only works with `<input type="text" />`.  It looks like all other types are explicitly excluded. This isn't ideal because I'd like to mask the value, and also change the keyboard to numeric on mobile. Can all other "textbox-like" inputs be added?

**Comment by jcope2013** [comment]
also interested in a solution

**Comment by Mottie** [comment]
The problem is that modern browsers have all decided to follow W3C specificiations and have removed the ability to get a value from `selectionStart`, `selectionEnd` and `setRangeText` for input type email and number ([reference](https://html.spec.whatwg.org/multipage/forms.html#do-not-apply); also see [this discussion](https://code.google.com/p/chromium/issues/detail?id=324360))

![2015-03-02 07_53_26-html standard](https://cloud.githubusercontent.com/assets/136959/6441974/ce1f7a6c-c0b1-11e4-8506-9102b3fe2d9d.png)

They only just realized the issue with not being able to get the selection (`select()`), so they recently added that back.

So, the only way to get around this is to not use an e-mail or number type input if you need javascript to determine the caret position.

**Comment by edatodi** [comment]
To get a numeric keypad try type="tel".

**Comment by reverence89** [comment]
Has this issue been fixed? I'd like to also be able to use type=number so that on mobile devices the numeric keyboard is used rather than a full keyboard.

**Comment by aeberlin** [comment]
Are there any workarounds for this? I would also like numeric keypad on mobile without sacrificing input mask support.

**Comment by RobinHerbots** [comment]
@aeberlin, 

See the comments above.  I added the supportsInputType option.  By adding number you can experiment with it.
