### ISSUE TITLE
How to implement mask for these numbers?

### ISSUE THREAD

**Issue by hobojoe** [RobinHerbots/Inputmask#840]
Hi,

I've been using this plugin for masks for a while and recently I tried to implement 2 different masks for the same input and couldn't do it.

It is for phone numbers. It should accept both (99) 99999-9999 and 0800-999-9999 (notice that it starts with 0800).

The main issue is that both masks have the same number of digits. How could I implement the masks so that it realizes the number starts with 0800 and then change the mask accordingly?

**Comment by RobinHerbots** [comment]
@hobojoe , 

You got mutiple options.  

You can keep checking the value and if it strts with 0800 you apply the new mask (0800-999-9999) or you create a custom definition which does the check.  Somethinh like (99)9z999-9999
where z checks if the chars before match 080 and in that case does not allow 0.  You define tha mask as ["(99) 9z999-9999", "0800-999-9999"]

It would be nice if the inputmask could make a best guess so that a mask like ["(99) 99999-9999", "0800-999-9999"] is sufficient.

I will keep the issue open, as a reminder for such a functionality.

**Comment by hobojoe** [comment]
Hi @RobinHerbots ,

I tried to implement your suggested approach but I couldn't get it to work.

See my fiddle below:
http://jsfiddle.net/2sxgrx5w/

If I enter '080', then it doesn't change the mask to the alternate one ('0800-...').

Am I doing something wrong?

Thanks

`$(document).ready(function() {

```
      Inputmask.extendDefinitions({
        'z': {
          validator: function(chrs, buffer, pos, strict, opts) {
            //debugger
            var cbuffer = buffer.buffer.slice(0);

            //cbuffer.splice(pos, 0, chrs);
            var bufferStr = cbuffer.join('');
            var numeros = bufferStr.match(/\d/g).join("");

            return numeros.length >= 3 && numeros.substr(0, 3) == '080' ? false : true;
          },
          cardinality: 1
        }
      });

      $("#txtId").inputmask({
        mask: ["(99) 9z999-9999", "0800-999-9999"]
      });
    });`
```

**Comment by RobinHerbots** [comment]
@hobojoe , 

Have a look at http://jsfiddle.net/2sxgrx5w/1/

You need the latest version from github to make this work in your project.
