### ISSUE TITLE
Email mask doesn't allow to go to the domain part by mouse

### ISSUE THREAD

**Issue by hiddenman** [RobinHerbots/Inputmask#885]
Hi,

Thank you again for the great product!
Ther is another little problem with email input mask:  when user types the first part of the email and want to switch to the domain part by clicking mouse button (yes, as you might know, most of the users never use keyboard and do even simple things by mouse), plugin doesn't allow that.  The only ways for users to type a domain:
- press right arrow key, so the cursor will move over the "@" symbol to the domain part
- type "@" symbol, so the cursor will also move to the right.

Please, allow using mouse for that.

Thank you.

**Comment by hiddenman** [comment]
Hi,

Do you confirm that problem?

Thank you.

**Comment by RobinHerbots** [comment]
Yes, it would be nice to allow for better mouse navigation for the emailmask.

**Comment by hiddenman** [comment]
Sorry for disturbing. When are you going to fix that? Do you need any help?

Thank you.

**Comment by hiddenman** [comment]
Seems to be not fixed yet, right?

Thank you.

**Comment by RobinHerbots** [comment]
@hiddenman , 

I first try to complete milestone 3.2.
When the issue is still open then it is on the todo list.  I will not forget.

**Comment by voidmain02** [comment]
This bug applies not only to the email mask, but to any dynamic mask.

The caret is always set to the closest valid part. The problem is that the algorithm does not consider empty is valid, although it should.

In my case mask is `\\\\a{*}\\\\a{*}\\\\a{*}\\\\a{*}\\\\a{*}`. I can't place caret to any position except first one.

Also If I set caret using the right arrow, type a value, and then start typing the text to the left, the previously entered text will move to the left.
So If I want to get `\\abc\\def\` value, the only way to do this is: press right arrow twice enter 'abc', press right twice again and finally enter 'def'.

**Comment by skorobkov** [comment]
Hi,
Any news?  

Thank you.

**Comment by hiddenman** [comment]
Hi,

Any news/plans?

Thank you.

**Comment by RobinHerbots** [comment]
@hiddenman, 

Fixed!!
